### ISSUE TITLE
Missing copyright and license

### ISSUE THREAD

**Issue by kapouer** [kripken/embenchen#1]
Hi,

there's a copy of embenchen in v8 4.5.103, which i'm reviewing for distribution as a debian package.
I don't find embenchen to have any copyright, nor any license.
Of course, i suppose they are inherited from emscripten, but being distributed separately,
embenchen should have its own copy of the license - unless you mean it to be protected
by default copyright law - which is very protective and forbid redistribution as it is done in
debian, in which case i'd just have to remove it from the tarball.
Thank you for any clarification.

**Comment by kripken** [comment]
Yes, it was meant to inherit the emscripten MIT license. Added now, thanks for the bug report.

**Comment by kapouer** [comment]
Right on time ! Thanks !
