### ISSUE TITLE
Update benchmarks to deal with no-dead-code rule

### ISSUE THREAD

**Issue by lars-t-hansen** [kripken/embenchen#2]
After the no-dead-code check landed in SpiderMonkey the benchmarks are no longer working:

> trying binaryen method: native-wasm
> failed to compile wasm module: CompileError: at offset 146: non-fallthrough instruction must be followed by end or else

Presumably the benchmarks must be recompiled.

cc @sunfishcode

**Comment by kripken** [comment]
Updated, should be ok now.
